- name: Kubernetes in Azure
  href: ./index.yml
- name: Übersicht
- name: Schnellstarts
  expanded: true
- name: Tutorials
- name: Konzepte
- name: Anleitungen
  items:
    - name: Dauerhafte Speicherung von Daten mit Azure Files
      href: ../../aks/azure-files-dynamic-pv.md?toc=/azure/container-service/kubernetes/toc.json
    - name: Überwachen
    - name: Bereitstellen von Spring Boot-Apps
      items:
        - name: Bereitstellen einer Spring Boot-Anwendung unter Linux in Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Bereitstellen einer Spring Boot-Anwendung in einem Kubernetes-Cluster in Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Bereitstellen einer Spring Boot-App unter Verwendung des fabric8 Maven-Plug-Ins
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Verweis
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Ressourcen
  items:
    - name: Azure-Roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Vorlagen – ACS Engine
      href: 'https://github.com/Azure/acs-engine'
    - name: Preise
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Regionale Verfügbarkeit
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videos
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'